# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
                ('try_time', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
